spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/mp_test?useSSL=false
#    url: jdbc:mysql://localhost:3306/mp_test?useSSL=false
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: root
#    type: com.alibaba.druid.pool.DruidDataSource




mybatis-plus:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#  config-location: classpath:mybatis-config.xml